FROM archlinux:latest
RUN pacman -Syu --noconfirm wget sudo fakeroot
RUN useradd -m builduser 
RUN passwd -d builduser 
RUN printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
RUN sudo -u builduser bash -c 'cd ~ && wget https://aur.archlinux.org/cgit/aur.git/snapshot/packettracer.tar.gz && tar -xvf packettracer.tar.gz && cd packettracer && wget -O CiscoPacketTracer_820_Ubuntu_64bit.deb https://archive.org/download/cisco-packet-tracer-820-ubuntu-64bit-696ae-64b-25/Cisco_Packet_Tracer_820_Ubuntu_64bit_696ae64b25.deb  && makepkg -si --noconfirm'
RUN userdel  builduser
RUN rm -rf /home/builduser
RUN pacman -Rns --noconfirm wget sudo  fakeroot
RUN pacman -Scc --noconfirm
CMD packettracer

# docker build -t pk .
# docker run -ti --rm --network none -e DISPLAY=$DISPLAY  -v /tmp/.X11-unix:/tmp/.X11-unix pk 
