version: '3.8'

services:
  webb:
    build: .
    image: web
    container_name: web
    environment:
      - ANDROID_SDK_ROOT=/opt/android-sdk
      - ANDROID_HOME=/opt/android-sdk
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk
    volumes:
      - /mnt/partition/docker/web:/data
    tty: true
    stdin_open: true
