FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive
RUN apt update -y && apt install -y wget  openjdk-19-jdk git xdg-utils maven
RUN wget https://download2.gluonhq.com/scenebuilder/19.0.0/install/linux/SceneBuilder-19.0.0.deb
RUN  mkdir /usr/share/desktop-directories/
RUN dpkg -i SceneBuilder-19.0.0.deb

# RUN apt update -y && apt install -y wget  default-jdk  git gnupg ca-certificates curl
# RUN wget https://dlcdn.apache.org/netbeans/netbeans-installers/17/apache-netbeans_17-1_all.deb 
# RUN dpkg -i apache-netbeans_17-1_all.deb
# RUN curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg
# RUN echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" |  tee /etc/apt/sources.list.d/zulu.list
# RUN apt -y update  && apt install -y zulu19-jdk
# CMD netbeans 