FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive
RUN apt -y update 
RUN  apt install -y openjdk-19-jdk git wget bzip2 libgtk-3-0 libdbus-glib-1-2 maven
RUN wget https://dlcdn.apache.org/netbeans/netbeans-installers/17/apache-netbeans_17-1_all.deb 
RUN dpkg -i apache-netbeans_17-1_all.deb
RUN wget https://download-installer.cdn.mozilla.net/pub/firefox/releases/111.0.1/linux-x86_64/en-US/firefox-111.0.1.tar.bz2
RUN tar -xvf firefox-111.0.1.tar.bz2
RUN mv firefox /opt
RUN ln -s /opt/firefox/firefox /usr/bin/firefox
RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.73/bin/apache-tomcat-9.0.73.tar.gz
RUN tar -xvf apache-tomcat-9.0.73.tar.gz
RUN mv apache-tomcat-9.0.73 /usr/share/tomcat9
RUN echo '<?xml version="1.0" encoding="UTF-8"?><tomcat-users xmlns="http://tomcat.apache.org/xml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd" version="1.0"><role rolename="manager-gui"/><user username="tomcat" password="tomcat" roles="manager-gui"/></tomcat-users>' > /usr/share/tomcat9/conf/tomcat-users.xml  
CMD /usr/share/tomcat9/bin/startup.sh && /bin/bash


#docker run -ti  -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /mnt/Partition/docker/java:/data -p 8080:8080 --name m8 jt
