FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive
RUN apt update -y && apt install -y wget  git xdg-utils maven  libgtk2.0-0 libpango1.0-0 libgdk-pixbuf2.0-0 libgl1-mesa-glx sqlite3
RUN wget https://download2.gluonhq.com/scenebuilder/19.0.0/install/linux/SceneBuilder-19.0.0.deb
RUN wget https://dlcdn.apache.org/netbeans/netbeans-installers/17/apache-netbeans_17-1_all.deb 
RUN wget https://cdn.azul.com/zulu/bin/zulu20.30.11-ca-fx-jdk20.0.1-linux_amd64.deb
RUN mkdir /usr/share/desktop-directories/
RUN dpkg -i SceneBuilder-19.0.0.deb
RUN dpkg -i apache-netbeans_17-1_all.deb
RUN echo 'export PATH=$PATH:/opt/scenebuilder/bin' >> ~/.bashrc
RUN apt remove -y openjdk-*
RUN dpkg -i zulu20.30.11-ca-fx-jdk20.0.1-linux_amd64.deb
RUN wget https://github.com/xerial/sqlite-jdbc/releases/download/3.41.2.1/sqlite-jdbc-3.41.2.1.jar 
