#visual-pardigm
FROM ubuntu
ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt install -y wget
RUN wget https://eu8.dl.visual-paradigm.com/visual-paradigm/vpce17.0/20230401/Visual_Paradigm_CE_17_0_20230401_Linux64.sh
RUN chmod +x Visual_Paradigm_CE_17_0_20230401_Linux64.sh
RUN apt install -y openjdk-19-jdk